fix: Fixed the way that gcl works

diff --git a/custom_scripts/.local/scripts/gcl b/custom_scripts/.local/scripts/gcl
--- a/custom_scripts/.local/scripts/gcl
+++ b/custom_scripts/.local/scripts/gcl
@@ -1,38 +1,25 @@
 #!/bin/sh
 # Date: 2024/05/22
-# Description: A git clone utility
-
-emails=("paul.lv.ohl@gmail.com" "paul.ohl@bedrockstreaming.com")
-userName="Paul Ohl"
+# Description: A git clone utility. Use with an alias for best results
+# alias gcl='. gcl'
 
 # Check if the user has provided a URL
 if [ -z "$1" ]; then
     echo "Please provide a URL"
-    exit 1
+else
+    # Exit if the user provides more than 2 arguments
+    if [ $# -gt 2 ]; then
+        echo "Too many arguments"
+    else
+
+        # Clone the repository
+        if ! git clone --recursive $@; then
+            echo "Failed to clone the repository"
+        else
+            directoryName=$([ $# -eq 2 ] && echo "$2" || basename "$1" .git)
+            cd "$directoryName" || return
+
+            gconf
+        fi
+    fi
 fi
-
-# Exit if the user provides more than 2 arguments
-if [ $# -gt 2 ]; then
-    echo "Too many arguments"
-    exit 1
-fi
-
-# Clone the repository
-git clone --recursive $@
-
-# Check if the clone was successful
-if ! [ $? -eq 0 ]; then
-    exit 1
-fi
-
-directoryName=$([ $# -eq 2 ] && echo "$2" || basename "$1" .git)
-cd "$directoryName" || exit 1
-
-selectedEmail=$(echo "${emails[@]}" | tr ' ' '\n' | fzf --algo=v1 --border --border-label="╢ Which address to use? ╟" --color=label:italic:black)
-if [ -z "$selectedEmail" ]; then
-    echo "No email selected"
-    exit 1
-fi
-
-git config user.email "$selectedEmail"
-git config user.name "$userName"
